CONTROLLER_NAMES = {
    "DualShock3": "DualShock 3 (PS3)",
    "DualShock4": "DualShock 4 (PS4)",
    "DualSense": "DualSense (PS5)",
    "DualSense": "DualSense (PS5)",
    "JoyCon": "Joy-Con",
    "JoyConL": "Joy-Con Left",
    "JoyConR": "Joy-Con Right",
    "SwitchPro": "Switch Pro Controller",
    "Steam": "Steam Controller",
    "Wii": "Wii Remote",
    "WiiNunchuck": "Wii Remote with Nunchuck",
    "Xbox360": "Xbox 360 Controller",
    "XboxOne": "Xbox One Controller",
    "XboxSeries": "Xbox Series Controller",
    "XboxElite": "Xbox Elite Controller",
    "XboxAdaptive": "Xbox Adaptive Controller",
}

BUTTON_NAMES = {
    "DualShock4": {
        0: 'Cross',
        1: 'Circle',
        2: 'Square',
        3: 'Triangle',
        4: 'L1',
        5: 'R1',
        6: 'L2',
        7: 'R2',
        8: 'Share',
        9: 'Options',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'PS',
        17: 'Pad',
        100: 'Left Stick Horizontal',
        101: 'Left Stick Vertical',
        102: 'Right Stick Horizontal',
        103: 'Right Stick Vertical',
        104: 'L2',
        105: 'R2',
    },

    "DualShock3": {
        0: 'Cross',
        1: 'Circle',
        2: 'Square',
        3: 'Triangle',
        4: 'L1',
        5: 'R1',
        6: 'L2',
        7: 'R2',
        8: 'Select',
        9: 'Start',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'PS',
        100: 'Left Stick Horizontal',
        101: 'Left Stick Vertical',
        102: 'Right Stick Horizontal',
        103: 'Right Stick Vertical',
        104: 'L2',
        105: 'R2',
    },

    "DualSense": {
        0: 'Cross',
        1: 'Circle',
        2: 'Square',
        3: 'Triangle',
        4: 'L1',
        5: 'R1',
        6: 'L2',
        7: 'R2',
        8: 'Select',
        9: 'Start',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'PS',
        17: 'Pad',
        100: 'Left Stick Horizontal',
        101: 'Left Stick Vertical',
        102: 'Right Stick Horizontal',
        103: 'Right Stick Vertical',
        104: 'L2',
        105: 'R2',
    },

    "XboxOne": {
        0: 'A',
        1: 'B',
        2: 'X',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'View',
        9: 'Menu',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'Xbox',
        100: 'Left Stick Horizontal',
        101: 'Left Stick Vertical',
        102: 'Right Stick Horizontal',
        103: 'Right Stick Vertical',
        104: 'Left Trigger',
        105: 'Right Trigger',
    },

    "XboxSeries": {
        0: 'A',
        1: 'B',
        2: 'X',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'View',
        9: 'Menu',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'Xbox',
        17: 'Share',
        100: 'Left Stick Horizontal',
        101: 'Left Stick Vertical',
        102: 'Right Stick Horizontal',
        103: 'Right Stick Vertical',
        104: 'Left Trigger',
        105: 'Right Trigger',
    },

    "Xbox360": {
        0: 'A',
        1: 'B',
        2: 'X',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'Back',
        9: 'Start',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'Xbox',
        100: 'Left Stick Horizontal',
        101: 'Left Stick Vertical',
        102: 'Right Stick Horizontal',
        103: 'Right Stick Vertical',
        104: 'Left Trigger',
        105: 'Right Trigger',
    },

    "Wii": {
        0: '1',
        1: '2',
        2: 'A',
        3: 'B',
        4: '+',
        5: '-',
        6: 'Home',
        100: 'D-Pad Vertical',
        101: 'D-Pad Horizontal',
        102: 'Pitch',
        103: 'Roll',
    },

    "WiiNunchuck": {
        0: 'A',
        1: 'B',
        2: 'C',
        3: 'Z',
        4: 'X',
        5: 'Y',
        6: '+',
        7: '-',
        8: 'Home',
        9: 'Nuchuck Stick?',
        10: '',
        11: '',
        12: '',
        13: 'D-Pad Up',
        14: 'D-Pad Down',
        15: 'D-Pad Left',
        16: 'D-Pad Right',
        100: 'Nunchuck Stick Horizontal',
        101: 'Nunchuck Stick Vertical',
        102: 'Pitch',
        103: 'Roll',
    },
}
