BUTTON_NAMES = {
    "DualShock 3": {
        0: 'Cross',
        1: 'Circle',
        2: 'Square',
        3: 'Triangle',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'Select',
        9: 'Start',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        100: 'Left Stick Left',
        101: 'Left Stick Right',
        102: 'Left Stick Up',
        103: 'Left Stick Down',
        104: 'Right Stick Left',
        105: 'Right Stick Right',
        106: 'Right Stick Up',
        107: 'Right Stick Down',

    },

    "DualShock 4": {
        0: 'Cross',
        1: 'Circle',
        2: 'Square',
        3: 'Triangle',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'Share',
        9: 'Options',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'PS',
        17: 'Pad',
        100: 'Left Stick Left',
        101: 'Left Stick Right',
        102: 'Left Stick Up',
        103: 'Left Stick Down',
        104: 'Right Stick Left',
        105: 'Right Stick Right',
        106: 'Right Stick Up',
        107: 'Right Stick Down',        
    },

    "DualSense": {
        0: 'Cross',
        1: 'Circle',
        2: 'Square',
        3: 'Triangle',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'Share',
        9: 'Options',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'PS',
        17: 'Pad',
        100: 'Left Stick Left',
        101: 'Left Stick Right',
        102: 'Left Stick Up',
        103: 'Left Stick Down',
        104: 'Right Stick Left',
        105: 'Right Stick Right',
        106: 'Right Stick Up',
        107: 'Right Stick Down',
    },

    "Xbox One": {
        0: 'A',
        1: 'B',
        2: 'X',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'View',
        9: 'Menu',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'Xbox',
        100: 'Left Stick Left',
        101: 'Left Stick Right',
        102: 'Left Stick Up',
        103: 'Left Stick Down',
        104: 'Right Stick Left',
        105: 'Right Stick Right',
        106: 'Right Stick Up',
        107: 'Right Stick Down',
    },

    "Xbox Series": {
        0: 'A',
        1: 'B',
        2: 'X',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'View',
        9: 'Menu',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'Xbox',
        17: 'Share',
        100: 'Left Stick Left',
        101: 'Left Stick Right',
        102: 'Left Stick Up',
        103: 'Left Stick Down',
        104: 'Right Stick Left',
        105: 'Right Stick Right',
        106: 'Right Stick Up',
        107: 'Right Stick Down',
    },

    "Xbox 360": {
        0: 'A',
        1: 'B',
        2: 'X',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'Back',
        9: 'Start',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'Xbox',
        100: 'Left Stick Left',
        101: 'Left Stick Right',
        102: 'Left Stick Up',
        103: 'Left Stick Down',
        104: 'Right Stick Left',
        105: 'Right Stick Right',
        106: 'Right Stick Up',
        107: 'Right Stick Down',
    },

    "Switch Pro": {
        0: 'A',
        1: 'B',
        2: 'X',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'Square',
        9: 'Home',
        10: 'Left Stick',
        11: 'Right Stick',
        12: 'D-Pad Up',
        13: 'D-Pad Down',
        14: 'D-Pad Left',
        15: 'D-Pad Right',
        16: 'Minus',
        17: 'Plus',
        100: 'Left Stick Left',
        101: 'Left Stick Right',
        102: 'Left Stick Up',
        103: 'Left Stick Down',
        104: 'Right Stick Left',
        105: 'Right Stick Right',
        106: 'Right Stick Up',
        107: 'Right Stick Down',
    },

    "Steam Controller": {
        0: 'A',
        1: 'B',
        2: 'X',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Left Trigger',
        7: 'Right Trigger',
        8: 'Back',
        9: 'Start',
        10: 'Stick',
        11: 'Right Track',
        12: 'Left Track Up',
        13: 'Left Track Down',
        14: 'Left Track Left',
        15: 'Left Track Right',
        16: 'Left Grip',
        17: 'Right Grip',
        18: 'Right Track Up',
        19: 'Right Track Down',
        20: 'Right Track Left',
        21: 'Right Track Right',
        100: 'Stick Left',
        101: 'Stick Right',
        102: 'Stick Up',
        103: 'Stick Down',
        22: 'Steam',
    },

    "Wii Remote": {
        0: '1',
        1: '2',
        2: 'A',
        3: 'B',
        4: 'Plus',
        5: 'Minus',
        6: 'Home',
        7: 'Z',
        100: "Roll",
        101: "Tilt"
    },

    # "Wii Nunchuck": {
    #     0: 'A',
    #     1: 'B',
    #     2: 'C',
    #     3: 'Z',
    #     4: 'X',
    #     5: 'Y',
    #     6: 'Plus',
    #     7: 'Minus',
    #     8: 'Home',
    #     9: 'Nuchuck Stick?',
    #     10: '',
    #     11: '',
    #     12: '',
    #     13: 'D-Pad Up',
    #     14: 'D-Pad Down',
    #     15: 'D-Pad Left',
    #     16: 'D-Pad Right',
    # },

    "Joy-Con Left": {
        0: 'A',
        1: 'X',
        2: 'B',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        9: 'Plus',
        11: 'Stick',
        12: 'Home',
        100: 'Stick Down',
        101: 'Stick Up',
        102: 'Stick Left',
        103: 'Stick Right',
    },

    "Joy-Con Right": {
        0: 'Down',
        1: 'Right',
        2: 'Left',
        3: 'Up',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        9: 'Minus',
        11: 'Stick',
        12: 'Capture',
        100: 'Stick Left',
        101: 'Stick Right',
        102: 'Stick Up',
        103: 'Stick Down',
    },
    
    "Joy-Con": {
        0: 'A',
        1: 'X',
        2: 'B',
        3: 'Y',
        9: 'Plus',
        11: 'Right Stick',
        12: 'Home',
        14: 'Right Shoulder',
        15: 'Right Trigger',
        16: 'Left',
        17: 'Down',
        18: 'Up',
        19: 'Right',
        24: 'Minus',
        26: 'Left Stick',
        28: 'Capture',
        30: 'Left Shoulder',
        31: 'Left Trigger' ,
        100: 'Left Stick Left',
        101: 'Left Stick Right',
        102: 'Left Stick Up',
        103: 'Left Stick Down',
        104: 'Right Stick Left',
        105: 'Right Stick Right',
        106: 'Right Stick Up',
        107: 'Right Stick Down',
    },

    "Super Nintendo": {
        0: 'B',
        1: 'X',
        2: 'A',
        3: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        8: 'Start',
        9: 'Select',
        100: 'D-Pad Up',
        101: 'D-Pad Down',
        102: 'D-Pad Left',
        103: 'D-Pad Right',
    },
}

AXES_NAMES = {
    "DualShock 3": {
        0: 'Left Stick Horizontal',
        1: 'Left Stick Vertical',
        2: 'Right Stick Horizontal',
        3: 'Right Stick Vertical',
    },

    "DualShock 4": {
        0: 'Left Stick Horizontal',
        1: 'Left Stick Vertical',
        2: 'Right Stick Horizontal',
        3: 'Right Stick Vertical',
    },

    "DualSense": {
        0: 'Left Stick Horizontal',
        1: 'Left Stick Vertical',
        2: 'Right Stick Horizontal',
        3: 'Right Stick Vertical',
    },

    "Xbox 360": {
        0: 'Left Stick Horizontal',
        1: 'Left Stick Vertical',
        2: 'Right Stick Horizontal',
        3: 'Right Stick Vertical',
    },

    "Xbox One": {
        0: 'Left Stick Horizontal',
        1: 'Left Stick Vertical',
        2: 'Right Stick Horizontal',
        3: 'Right Stick Vertical',
    },

    "Xbox Series": {
        0: 'Left Stick Horizontal',
        1: 'Left Stick Vertical',
        2: 'Right Stick Horizontal',
        3: 'Right Stick Vertical',
    },

    "Switch Pro": {
        0: 'Left Stick Horizontal',
        1: 'Left Stick Vertical',
        2: 'Right Stick Horizontal',
        3: 'Right Stick Vertical',
    },

    "Steam Controller": {
        0: 'Stick Horizontal',
        1: 'Stick Vertical',
    },

    "Joy-Con Left": {
        0: 'Left Stick Horizontal',
        1: 'Left Stick Vertical',
    },

    "Joy-Con Right": {
        0: 'Right Stick Horizontal',
        1: 'Right Stick Vertical',
    },

}